name: 'Headless'
description: 'Installs and configures modules for headless and the Gin admin theme.'
type: 'Site'

install:
  # Install core dependencies.
  - config
  - help
  # Install Claro as it is a dependency of Gin, but don't import config.
  - claro
  # Install Toolbar as it is a dependency of Gin Toolbar.
  - toolbar
  - admin_toolbar
  - admin_toolbar_search
  - admin_toolbar_tools
  # Install Gin theme and base modules that extend it.
  - gin
  - gin_login
  - gin_toolbar
  # Install additional modules from composer.json.
  - jsonapi_extras
  - jsonapi_image_styles
  - jsonapi_permission_access
  - jsonapi_resources
  - key_auth
  - login_security
  - openapi
  - openapi_jsonapi
  - openapi_ui
  - openapi_ui_redoc
  - paragraphs
  - password_policy
  - seckit
  - security_review
  - restui
  - simple_oauth

config:
  import:
    # Import all of Admin Toolbar's modules config.
    admin_toolbar: '*'
    admin_toolbar_search: '*'
    admin_toolbar_tools: '*'
    # Import all of Gin and Gin Login's config.
    # Gin Toolbar does not have any config.
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
  actions:
    # Set and unset Gin blocks.
    block.block.gin_site_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simple_config_update:
        status: false
    # Update the admin theme to Gin in Theme settings.
    system.theme:
      simple_config_update:
        admin: gin
